### ISSUE TITLE
The `Try Player` button on the landing page, takes you to the Documentation instead of actually "Trying out the player"

### ISSUE THREAD

**Issue by yxshv** [vidstack/site#22]

**Comment by mihar-22** [comment]
It'll be updated soon once we have a landing page for the player. Technically the docs will guide you on installing and trying the player. Maybe you're after a demo or something which we'll add to the player product page.

**Comment by yxshv** [comment]
> It'll be updated soon once we have a landing page for the player. Technically the docs will guide you on installing and trying the player. Maybe you're after a demo or something which we'll add to the player product page.

well it can be renamed to "Get Started" the button is misleading
