### ISSUE TITLE
Is this project open source?

### ISSUE THREAD

**Issue by piszczu4** [vidstack/site#24]
Hi @mihar-22 , your docs looks really amazing. Is it allowed to use some of your components within my personal project or not? Also, how did you choose so nice looking gradient text colors? Did you do it by trial and errors method or there is some `formula` or rules that I should follow?

**Comment by mihar-22** [comment]
Yes it’s open-source, feel free to use stuff. Honestly I just mess around in devtools until I get the right gradient.
