### ISSUE TITLE
1.0 Docs not accurate?

### ISSUE THREAD

**Issue by adampatarino** [vidstack/site#6]
I'm looking at upgrading to 1.0 but running into trouble with the unfinished docs. The main question I have is the difference between the component docs and what's used in the examples: 

[Docs](https://www.vidstack.io/docs/wc/player/components/buttons/play-button?styling=default-theme)
```
<media-play-button>
  <media-icon type="play"></media-icon>
  <media-icon type="pause"></media-icon>
  <media-icon type="replay"></media-icon>
</media-play-button>
```

[Examples](https://github.com/vidstack/examples/blob/main/player/web-components/default-theme/video-player.html):
```
 <media-play-button class="vds-button">
    <media-icon class="vds-play-icon" type="play"></media-icon>
    <media-icon class="vds-pause-icon" type="pause"></media-icon>
</media-play-button>
```

The docs don't mention needing classes, but all the examples include them. I'm able to figure it out using examples where a component is available to reference. However it's tedious to dig through the examples and find the proper CSS classes in order to get the default theme to work.

Am I missing something?

**Comment by mihar-22** [comment]
Hey @adampatarino! Working on the docs right now. I'm finally up to adding examples, you can see the first one for the [Poster](https://www.vidstack.io/docs/wc/player/components/display/poster?styling=default-theme). I'll be adding them for all components over this week. The default theme requires classes to be applied as shown in the examples. I know it's probably inconvenient checking the examples, but the docs should be ready soon! The API references are simply showing the general expected structure of a component and not how to style them.

**Comment by adampatarino** [comment]
Ok that makes sense! I wasn't sure if it was just not done yet, or I was implementing something wrong and the classes should have been automatically been pulled in.

Thanks!
